[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://aptoseidonback.onrender.com/:splat"
  status = 200

[build.environment]
  VITE_API_URL = "https://aptoseidonback.onrender.com"
  NODE_VERSION = "20"
